In [26]:
import pandas as pd
import numpy as np

Download the roster from Gradescope. **Don't** commit the roster to GitHub – let's avoid the possibility of accidentally releasing it to students.

In [27]:
roster = pd.read_csv('gradescope_enrolled.csv')
roster

,First Name,Last Name,SID,Email,Role,Section
0,NaN,Alia El Mansy,200336915,aelmansy@ucsd.edu,Student,DSC-010 - 003-002-DI
1,-,Lucas,200483927,hal287@ucsd.edu,Student,DSC-010 - 004-001-DI
2,Aadhi,Balakrishnan,200442915,aabalakrishnan@ucsd.edu,Student,DSC-010 - 001-001-DI
3,Aadhyathmik,Varahagiri,200453906,avarahagiri@ucsd.edu,Student,DSC-010 - 002-001-DI
4,Aadi,Gupta,200424957,aag043@ucsd.edu,Student,DSC-010 - 002-001-DI
...,...,...,...,...,...,...
477,Zichen,Xu,200425082,zix063@ucsd.edu,Student,DSC-010 - 003-001-DI
478,Zichuan,Xiao,200459454,zix071@ucsd.edu,Student,DSC-010 - 004-001-DI
479,Zifan,Li,200454737,zil190@ucsd.edu,Student,DSC-010 - 004-001-DI
480,Ziqin,Huang,200483933,zih075@ucsd.edu,Student,DSC-010 - 002-001-DI
481,Ziyu,Li,200455643,zil200@ucsd.edu,Student,DSC-010 - 004-001-DI

In [28]:
# drop first two rows because First Name is NaN and -
# handle this manually each quarter
roster = roster.take(np.arange(2, roster.shape[0]))

In [29]:
roster['Section'].value_counts()

Section
DSC-010 - 001-001-DI    134
DSC-010 - 002-001-DI    132
DSC-010 - 004-001-DI    129
DSC-010 - 003-001-DI     78
DSC-010 - 003-002-DI      5
DSC-010 - 002-001-LA      1
DSC-010 - 002-000-LE      1
Name: count, dtype: int64

In [30]:
# The lecture number is in positions 10, 11, and 12
# Example: 'DSC-010 - 004-001-DI' ==> 004
roster['Lecture'] = roster['Section'].str[10:13]
roster

,First Name,Last Name,SID,Email,Role,Section,Lecture
2,Aadhi,Balakrishnan,200442915,aabalakrishnan@ucsd.edu,Student,DSC-010 - 001-001-DI,001
3,Aadhyathmik,Varahagiri,200453906,avarahagiri@ucsd.edu,Student,DSC-010 - 002-001-DI,002
4,Aadi,Gupta,200424957,aag043@ucsd.edu,Student,DSC-010 - 002-001-DI,002
5,Aanya,Pandia,200483782,apandia@ucsd.edu,Student,DSC-010 - 004-001-DI,004
6,Aarav,Desai,200456250,aad019@ucsd.edu,Student,DSC-010 - 004-001-DI,004
...,...,...,...,...,...,...,...
477,Zichen,Xu,200425082,zix063@ucsd.edu,Student,DSC-010 - 003-001-DI,003
478,Zichuan,Xiao,200459454,zix071@ucsd.edu,Student,DSC-010 - 004-001-DI,004
479,Zifan,Li,200454737,zil190@ucsd.edu,Student,DSC-010 - 004-001-DI,004
480,Ziqin,Huang,200483933,zih075@ucsd.edu,Student,DSC-010 - 002-001-DI,002
481,Ziyu,Li,200455643,zil200@ucsd.edu,Student,DSC-010 - 004-001-DI,004

In [31]:
# For anonymity, use random last names
last_names = np.asarray(list(map(lambda x: ''.join(x).title(), 
                                 np.random.choice(list('abcdefghijklmnopqrstuvwxyz'), 
                                size=(roster.shape[0], 6)))))
last_names

array(['Lkfmyf', 'Agtsra', 'Dkaaij', 'Bneksj', 'Lelyvw', 'Tqfgwg',
       'Yyzmpz', 'Pkwcrs', 'Dfkibc', 'Iwuric', 'Beqjbt', 'Bnhmgb',
       'Rbkxaf', 'Itvuha', 'Ysizrf', 'Iyswjo', 'Zivzdf', 'Jqigsg',
       'Ghhukz', 'Ariwxt', 'Wehedx', 'Wcpgzf', 'Ezllue', 'Mfepyo',
       'Unnxxt', 'Iltwth', 'Jlmzjy', 'Ezjydb', 'Akqgct', 'Tvopmz',
       'Jhiztk', 'Rcdbpp', 'Qzmjlu', 'Itmexv', 'Bklqjb', 'Wdliuy',
       'Ovcqdx', 'Umddph', 'Mjlwbn', 'Qeicig', 'Cdfxir', 'Hkmgfh',
       'Sushra', 'Lrdbpp', 'Iacmqj', 'Gowmpm', 'Ooafit', 'Hmqrgt',
       'Zcwvuy', 'Mqixtk', 'Pnqabh', 'Ddbgxv', 'Mqgpuj', 'Uoioar',
       'Vlwjnc', 'Geggsi', 'Ixkhrh', 'Xgvqdn', 'Wheczf', 'Mstnzu',
       'Nbjnvr', 'Ifguua', 'Pczaxl', 'Pbnejb', 'Gdswjw', 'Fzptdi',
       'Acupaw', 'Miwzrj', 'Zjwgke', 'Uqrwvg', 'Sewrpo', 'Pnugil',
       'Xvrvym', 'Jslqdg', 'Djlwlr', 'Zopxts', 'Nfmvlo', 'Aylwkt',
       'Dkvnhk', 'Dzeyns', 'Xqzwqm', 'Tbeuvb', 'Hnjdkq', 'Sktsvb',
       'Ovausc', 'Yijekn', 'Nnupyi', 'Meliht', 'Oldlcd', 'Pmsyfy',
       'Vixzyl', 'Pxtnoc', 'Jmylbd', 'Zbmwkz', 'Jnpgxc', 'Wevfjy',
       'Odeaib', 'Xmzzjf', 'Yyjkxg', 'Gewxdb', 'Hwkuip', 'Eypvim',
       'Jjwcrr', 'Trcgsb', 'Wldvzd', 'Tewuqq', 'Vmsybq', 'Zmnhhl',
       'Xlbtok', 'Kijeid', 'Ypcqer', 'Afljqw', 'Icxvsv', 'Wyhiof',
       'Vnzklm', 'Twqlmb', 'Hdouqw', 'Hgfuud', 'Detfwk', 'Enxenv',
       'Ceigsj', 'Vntjaf', 'Jcvwtz', 'Gczpbe', 'Eofgso', 'Wkdnra',
       'Ocwvcc', 'Jiymgw', 'Duuvas', 'Adqjsh', 'Hhdcgs', 'Fjvnut',
       'Vkcmhv', 'Kformc', 'Gkdtvl', 'Eztqum', 'Ebaahw', 'Oxczcy',
       'Glmnfp', 'Npbiab', 'Jftlpb', 'Mbbcml', 'Iecvku', 'Refdjg',
       'Ovfubp', 'Gmbmbr', 'Uldaly', 'Afmfnq', 'Ybgbgx', 'Pbnsnu',
       'Bkarba', 'Qegemj', 'Iegmxr', 'Cxneho', 'Gngqda', 'Cpoiql',
       'Fvrmgr', 'Vahfyh', 'Nzhjul', 'Xeulns', 'Qjlhlk', 'Bzstxs',
       'Eedjhi', 'Nmczlu', 'Ynvhsx', 'Codsrt', 'Inhpkt', 'Kkzicr',
       'Xcrwny', 'Ofcskt', 'Ktbybp', 'Eecxwj', 'Memlpx', 'Rgcugp',
       'Dxncjx', 'Mwzeyq', 'Bbcoxp', 'Eoshex', 'Lbriqd', 'Thdbfj',
       'Pwexoa', 'Gzakgb', 'Pjhxwm', 'Qjxdsb', 'Ksdrra', 'Cineov',
       'Bizfot', 'Dxcfrq', 'Hzzewi', 'Zjuzjq', 'Wevavk', 'Nrfzdl',
       'Rkiepq', 'Cfoexg', 'Gnktxc', 'Ohcnmv', 'Dpkapy', 'Dzaqqg',
       'Nzseow', 'Ujxheo', 'Ycrcxl', 'Ctkvnc', 'Wbsxen', 'Xyvboj',
       'Gxqgjv', 'Jzionw', 'Krnxjs', 'Osyutb', 'Yfhyfa', 'Cjyssm',
       'Rsscml', 'Migaep', 'Asjawi', 'Hsiunl', 'Nuwxkx', 'Lxcbjx',
       'Vqfnyu', 'Xooswg', 'Patpsl', 'Hvljii', 'Arzwma', 'Hnvoyr',
       'Zquory', 'Mbjfav', 'Elwwkt', 'Brkdnw', 'Gdrani', 'Jbfegx',
       'Adgipd', 'Aswalt', 'Euaoyo', 'Mdflvj', 'Vnaukk', 'Moiyxd',
       'Kxqgis', 'Uvxvpo', 'Wzcxou', 'Oezzbr', 'Qmpter', 'Ologpz',
       'Sycbof', 'Xyulnj', 'Pwemmn', 'Ysolyw', 'Kjiuov', 'Xqmsde',
       'Likjvj', 'Qzrild', 'Xpeema', 'Hpwyzv', 'Wwmnlt', 'Lkjehd',
       'Umqldz', 'Sksjbi', 'Npmmvj', 'Kcbbgl', 'Llvedc', 'Ofpqbj',
       'Rrzkcc', 'Zraboy', 'Eeqfgp', 'Kzgpfb', 'Eqmnio', 'Ifucbn',
       'Xhjfng', 'Sxsyla', 'Ytstkl', 'Kuzwdo', 'Xoypkh', 'Ylpvul',
       'Klhvom', 'Pzlbgv', 'Epxaxi', 'Zrlumt', 'Kfhzwf', 'Mrhseh',
       'Lyowox', 'Kmfriv', 'Bzheqy', 'Tiuccl', 'Mugbas', 'Zcambn',
       'Sefagg', 'Oyznrj', 'Ciugrw', 'Rsbmrp', 'Qlxdko', 'Xgdiea',
       'Qerxoh', 'Buzcdl', 'Nrjdoo', 'Xqagcr', 'Dfrvdx', 'Bbqqrf',
       'Maqruk', 'Eqwlgu', 'Bsubgo', 'Xycoba', 'Tzcymj', 'Maebiu',
       'Waocao', 'Pdwlsu', 'Cftisr', 'Gyfmee', 'Zenwys', 'Hdxsmn',
       'Wqvoyp', 'Tzvhzw', 'Fndnnj', 'Siypbf', 'Dfgmul', 'Nvmdqg',
       'Pfjegi', 'Fjbuwq', 'Eyouna', 'Uiscah', 'Uyslak', 'Nyalvb',
       'Wyglpu', 'Gmvyph', 'Jdffxn', 'Rlihgf', 'Caopkb', 'Wnkifc',
       'Aifiun', 'Myxbaj', 'Zfiiuw', 'Nagehz', 'Iuwphb', 'Adgheg',
       'Oosktp', 'Acabyj', 'Bxkevw', 'Jeczuk', 'Haxccb', 'Ayyrra',
       'Wjkuuv', 'Iwrkkk', 'Cksxjf', 'Iblgoo', 'Nnppgu', 'Dgqydp',
       'Apyyrr', 'Emalrq', 'Gdxwtz', 'Ymxbsd', 'Qefpod', 'Bgiroc',
       'Gwpglw', 'Mznqfi', 'Pztaxw', 'Mqzxmj', 'Npxdqa', 'Pnvaqf',
       'Sgudmx', 'Gweddv', 'Rnbevj', 'Wkfbeq', 'Hmbelk', 'Hixjxh',
       'Qbsaty', 'Ofygdb', 'Yjwgio', 'Egafot', 'Rwrjeh', 'Cfqsdd',
       'Cwzzkx', 'Mlcobb', 'Ftxaws', 'Axajlm', 'Lvomay', 'Eydvce',
       'Pdgtyd', 'Uaqfys', 'Faggok', 'Lujrjm', 'Kqfkik', 'Miymfg',
       'Zcnvyh', 'Fkzuki', 'Ogcmko', 'Awftuc', 'Rdldwe', 'Jhhhxy',
       'Rrnijv', 'Nahuyg', 'Avovwj', 'Gujknx', 'Hgqucr', 'Uteguk',
       'Hhqnax', 'Nyyvuo', 'Hqufon', 'Vfdjik', 'Ehraya', 'Fxffqj',
       'Penkkv', 'Pkodni', 'Hylpze', 'Qllhqn', 'Mgslqf', 'Ucslst',
       'Omipbn', 'Bbfddj', 'Byqybo', 'Zbcnsa', 'Wmgimx', 'Kdhjlr',
       'Lepffc', 'Ovvgab', 'Vknyci', 'Httirb', 'Yeyqxs', 'Gittiw',
       'Lnrxjh', 'Nsrqob', 'Odttih', 'Yletjs', 'Qceeqw', 'Ncewtq',
       'Mzbpzc', 'Mxqtom', 'Nhwpfq', 'Mqkhgb', 'Eojzwz', 'Glyrcy',
       'Edfhqc', 'Zahgzv', 'Hlzgoj', 'Hsqddg', 'Mbfmpb', 'Hunmig',
       'Avjbzo', 'Qglgkh', 'Qntwja', 'Izasjl', 'Blanwf', 'Unatgu',
       'Pwaxqs', 'Ipvndz', 'Lgpypv', 'Aplkgr', 'Bizbez', 'Rprqzl',
       'Ppuwnx', 'Ejfxmp', 'Meceka', 'Mcufic', 'Ivlgpg', 'Pjwsje',
       'Fnhmah', 'Czbjnm', 'Lewytl', 'Xgsmbc', 'Cpjwfj', 'Krkbpf',
       'Hgwftf', 'Wumlfc', 'Lqyiki', 'Ugsvjk', 'Cvvjjt', 'Bbxwoh',
       'Yswxad', 'Foelmd', 'Uyiebt', 'Jbwfkc', 'Ottjmv', 'Lcklhp',
       'Pqoxur', 'Gfcwwk', 'Awqnap', 'Hymyri', 'Bekuyl', 'Udlfmd',
       'Akvrbj', 'Epmkxq', 'Vtgplm', 'Wzqsnf', 'Lzdcsk', 'Lhlccu'],
      dtype='<U6')

In [32]:
roster['Student'] = (roster.get('First Name') + ' ' +  last_names)
roster

,First Name,Last Name,SID,Email,Role,Section,Lecture,Student
2,Aadhi,Balakrishnan,200442915,aabalakrishnan@ucsd.edu,Student,DSC-010 - 001-001-DI,001,Aadhi Lkfmyf
3,Aadhyathmik,Varahagiri,200453906,avarahagiri@ucsd.edu,Student,DSC-010 - 002-001-DI,002,Aadhyathmik Agtsra
4,Aadi,Gupta,200424957,aag043@ucsd.edu,Student,DSC-010 - 002-001-DI,002,Aadi Dkaaij
5,Aanya,Pandia,200483782,apandia@ucsd.edu,Student,DSC-010 - 004-001-DI,004,Aanya Bneksj
6,Aarav,Desai,200456250,aad019@ucsd.edu,Student,DSC-010 - 004-001-DI,004,Aarav Lelyvw
...,...,...,...,...,...,...,...,...
477,Zichen,Xu,200425082,zix063@ucsd.edu,Student,DSC-010 - 003-001-DI,003,Zichen Epmkxq
478,Zichuan,Xiao,200459454,zix071@ucsd.edu,Student,DSC-010 - 004-001-DI,004,Zichuan Vtgplm
479,Zifan,Li,200454737,zil190@ucsd.edu,Student,DSC-010 - 004-001-DI,004,Zifan Wzqsnf
480,Ziqin,Huang,200483933,zih075@ucsd.edu,Student,DSC-010 - 002-001-DI,002,Ziqin Lzdcsk
481,Ziyu,Li,200455643,zil200@ucsd.edu,Student,DSC-010 - 004-001-DI,004,Ziyu Lhlccu

In [33]:
roster = roster.get(['Student', 'Lecture', 'First Name'])
roster.columns=['name', 'section', 'first']
roster

                   name section        first
2          Aadhi Lkfmyf     001        Aadhi
3    Aadhyathmik Agtsra     002  Aadhyathmik
4           Aadi Dkaaij     002         Aadi
5          Aanya Bneksj     004        Aanya
6          Aarav Lelyvw     004        Aarav
..                  ...     ...          ...
477       Zichen Epmkxq     003       Zichen
478      Zichuan Vtgplm     004      Zichuan
479        Zifan Wzqsnf     004        Zifan
480        Ziqin Lzdcsk     002        Ziqin
481         Ziyu Lhlccu     004         Ziyu

[480 rows x 3 columns]

In [34]:
roster = roster.sample(frac=1).reset_index(drop=True) # So it's not alphabetically sorted
roster

                 name section      first
0      Matthew Mrhseh     001    Matthew
1        Zifan Wzqsnf     004      Zifan
2       Yourui Hgwftf     001     Yourui
3         John Vqfnyu     002       John
4       Rachel Iuwphb     001     Rachel
..                ...     ...        ...
475  Tan Thanh Qllhqn     002  Tan Thanh
476        Qiu Myxbaj     004        Qiu
477     Daryll Trcgsb     002     Daryll
478       Paul Pfjegi     004       Paul
479    Amolika Jlmzjy     004    Amolika

[480 rows x 3 columns]

In [35]:
roster.to_csv('../data/roster-anon.csv', index=False)

In [36]:
def first_name(full_name):
    return full_name.split(' ')[0]

In [37]:
with_first = roster.assign(first=roster['name'].apply(first_name))

In [38]:
first_counts = with_first.groupby('first').count().sort_values('name', ascending=False)

In [39]:
def how_many_others_in_section(name):
    row = with_first[roster['name'] == name]
    first = row.get('first').iloc[0]
    section = row.get('section').iloc[0]
    return with_first[(with_first.get('section') == section) & (with_first.get('first') == first)].shape[0]

In [40]:
with_others = with_first.assign(others=with_first.get('name').apply(how_many_others_in_section))
with_others

                 name section    first  others
0      Matthew Mrhseh     001  Matthew       3
1        Zifan Wzqsnf     004    Zifan       1
2       Yourui Hgwftf     001   Yourui       1
3         John Vqfnyu     002     John       1
4       Rachel Iuwphb     001   Rachel       1
..                ...     ...      ...     ...
475  Tan Thanh Qllhqn     002      Tan       1
476        Qiu Myxbaj     004      Qiu       1
477     Daryll Trcgsb     002   Daryll       1
478       Paul Pfjegi     004     Paul       1
479    Amolika Jlmzjy     004  Amolika       1

[480 rows x 4 columns]

In [41]:
with_others[with_others.get('others') > 1].sort_values('others', ascending=False)

                 name section      first  others
0      Matthew Mrhseh     001    Matthew       3
7    Stephanie Uteguk     003  Stephanie       3
102    Matthew Zrlumt     001    Matthew       3
123  Stephanie Hgqucr     003  Stephanie       3
253  Stephanie Gujknx     003  Stephanie       3
360    Matthew Kfhzwf     001    Matthew       3
23       Emily Eofgso     004      Emily       2
8        Dylan Twqlmb     002      Dylan       2
83      Bianca Acupaw     001     Bianca       2
32      Nathan Bsubgo     003     Nathan       2
28      Bianca Miwzrj     001     Bianca       2
130      Bryan Zopxts     003      Bryan       2
159       Eric Ocwvcc     004       Eric       2
175     Olivia Fndnnj     001     Olivia       2
181      Jacob Qjxdsb     001      Jacob       2
111      Jerry Ycrcxl     001      Jerry       2
217       Eric Jiymgw     004       Eric       2
229      Jimmy Cjyssm     004      Jimmy       2
245      Bryan Nfmvlo     003      Bryan       2
242     George Gmbmbr     001     George       2
247       Sean Egafot     004       Sean       2
262       Sean Yjwgio     004       Sean       2
264      Jimmy Yfhyfa     004      Jimmy       2
151     George Uldaly     001     George       2
274    Michael Ciugrw     001    Michael       2
296      Xinyu Bizbez     002      Xinyu       2
327      Emily Gczpbe     004      Emily       2
313    Michael Sefagg     001    Michael       2
333      Jerry Nzseow     001      Jerry       2
347      Dylan Hdouqw     002      Dylan       2
369     Olivia Tzvhzw     001     Olivia       2
370     Nathan Xycoba     003     Nathan       2
394      Kevin Qmpter     004      Kevin       2
396      Jacob Pjhxwm     001      Jacob       2
397     Justin Jbfegx     004     Justin       2
412     Justin Adgipd     004     Justin       2
422      Kevin Ologpz     004      Kevin       2
439       Ryan Emalrq     004       Ryan       2
440       Ryan Ymxbsd     004       Ryan       2
468      Xinyu Rprqzl     002      Xinyu       2

In [42]:
for_last_slide = with_first.groupby(['first', 'section']).count().sort_values('name', ascending=False).reset_index()
for_last_slide[for_last_slide.get('name')>1]

        first section  name
0     Matthew     001     3
1   Stephanie     003     3
2       Dylan     002     2
3       Emily     004     2
4      George     001     2
5       Jacob     001     2
6       Bryan     003     2
7        Eric     004     2
8      Bianca     001     2
9       Jimmy     004     2
10      Kevin     004     2
11      Jerry     001     2
12     Justin     004     2
13    Michael     001     2
14     Nathan     003     2
15     Olivia     001     2
16       Ryan     004     2
17       Sean     004     2
18      Xinyu     002     2